fix: enhance smoke test to wait for application readiness and improve error handling

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -114,12 +114,24 @@ jobs:
           load: true
           push: false
           tags: ${{ steps.meta.outputs.tags }}
-       
+       #smoke test will run the container and check if the /docs endpoint is reachable
       - name: run smoke test
         run: |
           docker run -d --name smart-delivery-test -p 8000:8000 ${{ steps.meta.outputs.tags }}
-          sleep 15
-          curl -f http://localhost:8000/docs || exit 1
+          echo "waiting for application to become healthy at http://localhost:8000/docs"
+          timeout=60
+          #loop to wait for the application to be ready
+          while ! curl -s -f http://localhost:8000/docs > /dev/null; do
+            timeout=$((timeout-5)) 
+            if [ $timeout -le 0 ]; then
+              echo "error: Timed out waiting for application."
+              echo "container Logs (smart-delivery-test) "
+              docker logs smart-delivery-test  
+              exit 1
+            fi
+            echo "still waiting ($timeout seconds left)"
+            sleep 10
+          done
 
       - name: push Docker Image to Docker Hub
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
